name: Build Python Package

on:
  push:
    tags: ["v*.*"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
    
    - name: Build package
      run:
        uv build

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
